//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dozorowania
    {
        public int id { get; set; }
        public Nullable<System.DateTime> data_rozpoczecia { get; set; }
        public Nullable<System.DateTime> data_zakonczenia { get; set; }
        public Nullable<int> id_dozorcy { get; set; }
        public Nullable<int> id_budynku { get; set; }
    
        public virtual Budynki Budynki { get; set; }
        public virtual Dozorcy Dozorcy { get; set; }
    }
}
